const categories = [
  {
    id: 'Cocina',
    name: 'Cocina',
    products: [
      {
        id: '1',
        name: 'Bajo mesada flotante',
        description: 'Mueble de cocina elegante y funcional, ideal para organizar tus utensilios.',
        price: 29999.99,
        image: '/images/cocina1.jpg',
      },
      {
        id: '2',
        name: 'Bajomesada con patas',
        description: 'Mueble de cocina con diseño clásico y espacio para almacenar tus productos.',
        price: 24999.99,
        image: '/images/cocina2.jpg',
      },
      {
        id: '3',
        name: 'Alacena',
        description: 'Alacena espaciosa para guardar tus alimentos y utensilios de cocina.',
        price: 24999.99,
        image: '/images/cocina3.jpg',
      },
      {
        id: '4',
        name: 'Despensero',
        description: 'Organizador versátil para tu cocina, perfecto para mantener tus productos en orden.',
        price: 28999.99,
        image: '/images/cocina4.jpg',
      },
      {
        id: '5',
        name: 'Bodega',
        description: 'Mueble con espacio para tus botellas de vino y copas, una adición elegante a tu hogar.',
        price: 28999.99,
        image: '/images/cocina5.jpg',
      },
    ],
  },
  {
    id: 'Habitacion',
    name: 'Habitación',
    products: [
      {
        id: '1',
        name: 'Cama de 1 plaza',
        description: 'Cama individual perfecta para una habitación juvenil o de invitados.',
        price: 199000,
        image: '/images/habitacion1.jpg',
      },
      {
        id: '2',
        name: 'Cama de 2 plazas',
        description: 'Cama doble con un diseño cómodo y elegante para tu habitación principal.',
        price: 349000,
        image: '/images/habitacion2.jpg',
      },
      {
        id: '3',
        name: 'Cucheta',
        description: 'Cama litera ideal para habitaciones compartidas o para ahorrar espacio.',
        price: 330000,
        image: '/images/habitacion3.jpg',
      },
      {
        id: '4',
        name: 'Cómoda',
        description: 'Mueble de almacenamiento con cajones espaciosos, perfecto para tu ropa.',
        price: 250000,
        image: '/images/habitacion4.jpg',
      },
      {
        id: '5',
        name: 'Chifonier',
        description: 'Mueble alto y delgado con múltiples cajones para organizar tus pertenencias.',
        price: 150000,
        image: '/images/habitacion5.jpg',
      },
    ],
  },
  {
    id: 'Living',
    name: 'Living',
    products: [
      {
        id: '1',
        name: 'Sillón de 3 cuerpos',
        description: 'Sofá amplio y cómodo para tu sala de estar.',
        price: 499000,
        image: '/images/living1.jpg',
      },
      {
        id: '2',
        name: 'Sillón de 2 cuerpos',
        description: 'Sofá compacto y elegante para tu sala de estar.',
        price: 399000,
        image: '/images/living2.jpg',
      },
      {
        id: '3',
        name: 'Mesa ratona',
        description: 'Mesa de centro moderna para acompañar tus sofás.',
        price: 149000,
        image: '/images/living3.jpg',
      },
      {
        id: '4',
        name: 'Futón',
        description: 'Futón convertible ideal para espacios pequeños.',
        price: 350000,
        image: '/images/living4.jpg',
      },
      {
        id: '5',
        name: 'Rack TV',
        description: 'Mueble para TV con espacio de almacenamiento.',
        price: 600000,
        image: '/images/living5.jpg',
      },
    ],
  },
  {
    id: 'Comedor',
    name: 'Comedor',
    products: [
      {
        id: '1',
        name: 'Sillas de madera',
        description: 'Sillas de comedor de madera maciza.',
        price: 20000,
        image: '/images/comedor1.jpg',
      },
      {
        id: '2',
        name: 'Sillas tapizadas',
        description: 'Sillas de comedor con tapizado elegante.',
        price: 30000,
        image: '/images/comedor2.jpg',
      },
      {
        id: '3',
        name: 'Mesa de Madera',
        description: 'Mesa de comedor de madera resistente.',
        price: 600000,
        image: '/images/comedor3.jpg',
      },
      {
        id: '4',
        name: 'Mesa de Vidrio',
        description: 'Mesa de comedor con tapa de vidrio templado.',
        price: 600000,
        image: '/images/comedor4.jpg',
      },
      {
        id: '5',
        name: 'Combo Desayunador con 2 banquetas',
        description: 'Mueble desayunador con espacio para dos personas.',
        price: 350000,
        image: '/images/comedor5.jpg',
      },
    ],
  },
  {
    id: 'Baño',
    name: 'Baño',
    products: [
      {
        id: '1',
        name: 'Perchero',
        description: 'Perchero de pared para colgar toallas y ropa.',
        price: 25000,
        image: '/images/baño1.jpg',
      },
      {
        id: '2',
        name: 'Vanitory flotante',
        description: 'Mueble de baño con lavabo flotante.',
        price: 199000,
        image: '/images/baño2.jpg',
      },
      {
        id: '3',
        name: 'Vanitory con patas',
        description: 'Mueble de baño con lavabo y patas de diseño.',
        price: 249000,
        image: '/images/baño3.jpg',
      },
      {
        id: '4',
        name: 'Organizador escalera',
        description: 'Estante de baño estilo escalera para tus accesorios.',
        price: 59000,
        image: '/images/baño4.jpg',
      },
      {
        id: '5',
        name: 'Toallero de madera',
        description: 'Toallero de baño de madera natural.',
        price: 90000,
        image: '/images/baño5.jpg',
      },
    ],
  }
];

export default categories;

